<?php
const AUTHOR = "Markus Schröder";
const MVC_VERSION = "1.0.0";

const PATH_ROOT = "..".DIRECTORY_SEPARATOR;
const PATH_LIB = PATH_ROOT."lib".DIRECTORY_SEPARATOR;
const PATH_CONTROLLER_ROOT = PATH_ROOT."controller".DIRECTORY_SEPARATOR;
const PATH_CONTROLLER = PATH_CONTROLLER_ROOT.SUB_DOMAIN.DIRECTORY_SEPARATOR;
const PATH_MODELS = PATH_ROOT."models".DIRECTORY_SEPARATOR;
const PATH_VIEWS_ROOT = PATH_ROOT."views".DIRECTORY_SEPARATOR;
const PATH_VIEWS = PATH_VIEWS_ROOT.SUB_DOMAIN.DIRECTORY_SEPARATOR;
const PATH_LOGS = PATH_ROOT."logs".DIRECTORY_SEPARATOR;
const PATH_CACHE_ROOT = PATH_ROOT."cache".DIRECTORY_SEPARATOR;
const PATH_CACHE = PATH_CACHE_ROOT.SUB_DOMAIN.DIRECTORY_SEPARATOR;

const PATH_PUBLIC_ROOT = DIRECTORY_SEPARATOR;
const PATH_PUBLIC = DIRECTORY_SEPARATOR.SUB_DOMAIN.DIRECTORY_SEPARATOR;

const PATH_SRC = PATH_PUBLIC_ROOT."src".DIRECTORY_SEPARATOR;
const PATH_CSS = PATH_PUBLIC."css".DIRECTORY_SEPARATOR;
const PATH_IMAGES = PATH_PUBLIC."images".DIRECTORY_SEPARATOR;
const PATH_JS = PATH_PUBLIC."js".DIRECTORY_SEPARATOR;
