<?php
const PATH_ROOT = "..".DIRECTORY_SEPARATOR;
const PATH_CONTROLLER_ROOT = PATH_ROOT."controller".DIRECTORY_SEPARATOR;
const PATH_CONTROLLER = PATH_CONTROLLER_ROOT.SUB_DOMAIN.DIRECTORY_SEPARATOR;
const PATH_MODELS = PATH_ROOT."models".DIRECTORY_SEPARATOR;
const PATH_VIEWS = PATH_ROOT."views".DIRECTORY_SEPARATOR.SUB_DOMAIN.DIRECTORY_SEPARATOR;
const PATH_LOGS = PATH_ROOT."logs".DIRECTORY_SEPARATOR;

const PATH_PUBLIC_ROOT = ".".DIRECTORY_SEPARATOR;
const PATH_SRC = PATH_PUBLIC_ROOT."src".DIRECTORY_SEPARATOR;
const PATH_PUBLIC = PATH_PUBLIC_ROOT.SUB_DOMAIN.DIRECTORY_SEPARATOR;
const PATH_CSS = PATH_PUBLIC."css".DIRECTORY_SEPARATOR;
const PATH_IMAGES = PATH_PUBLIC."images".DIRECTORY_SEPARATOR;
const PATH_JS = PATH_PUBLIC."js".DIRECTORY_SEPARATOR;
