<?php
const PATH_ROOT = "..".DIRECTORY_SEPARATOR;
const PATH_CONTROLLER = PATH_ROOT."controller".DIRECTORY_SEPARATOR;
const PATH_MODELS = PATH_ROOT."models".DIRECTORY_SEPARATOR;
const PATH_VIEWS = PATH_ROOT."views".DIRECTORY_SEPARATOR;

const PATH_PUBLIC = ".".DIRECTORY_SEPARATOR;
const PATH_CSS = PATH_PUBLIC."css".DIRECTORY_SEPARATOR;
const PATH_IMAGES = PATH_PUBLIC."images".DIRECTORY_SEPARATOR;
const PATH_JS = PATH_PUBLIC."js".DIRECTORY_SEPARATOR;